# Generated by Django 2.1 on 2018-09-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='gm_set',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='player_set',
        ),
    ]
