# Generated by Django 2.1 on 2018-09-09 13:51

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='name', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=core.utils.make_slug, editable=False, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=core.utils.make_slug, editable=False, max_length=25, unique=True),
        ),
    ]
