# Generated by Django 2.1 on 2018-09-26 21:07

from django.db import migrations
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180909_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True),
        ),
    ]
