# Generated by Django 2.1.2 on 2018-10-19 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
        ('accounts', '0003_auto_20180926_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='active_encounter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_active_in', to='plot.Encounter'),
        ),
    ]
