# Generated by Django 2.1 on 2018-09-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180926_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
