# Generated by Django 2.2b1 on 2019-02-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='joiner_assumed_email',
        ),
        migrations.AddField(
            model_name='invitation',
            name='joiner_external_identifier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
