# Generated by Django 2.1 on 2018-08-22 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('gm_set', models.ManyToManyField(editable=False, related_name='campaigns_gm_of', to=settings.AUTH_USER_MODEL)),
                ('player_set', models.ManyToManyField(related_name='campaigns_player_of', to=settings.AUTH_USER_MODEL)),
                ('record_owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='plot_campaign_owned_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
