# Generated by Django 2.1.2 on 2018-10-19 03:26

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20180926_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('campaign', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='plot_encounter_owned_set', to='accounts.Campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
