# Generated by Django 2.1.2 on 2018-11-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
