# Generated by Django 2.1 on 2018-08-22 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_auto_20180822_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='player_set',
            field=models.ManyToManyField(editable=False, related_name='campaigns_player_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
