# Generated by Django 2.1 on 2018-09-09 14:36

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180909_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combatant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default=core.utils.make_slug, editable=False, max_length=25, unique=True)),
                ('name', models.CharField(max_length=31)),
                ('initiative', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('loot', models.TextField(blank=True, null=True)),
                ('effects', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='combat_combatant_owned_set', to='accounts.Campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
