# Generated by Django 2.1.2 on 2018-10-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatant',
            name='max_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
