# Generated by Django 2.1 on 2018-09-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0002_combatant_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatant',
            name='slug',
        ),
    ]
