# Generated by Django 2.1.2 on 2018-10-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
        ('combat', '0002_combatant_max_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatant',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plot.Encounter'),
        ),
    ]
