# Generated by Django 2.1.2 on 2018-10-27 21:53

from django.db import migrations
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0005_gmscreentab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmscreentab',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True),
        ),
    ]
