# Generated by Django 2.1.2 on 2018-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0006_auto_20181027_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmscreentab',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
