# Generated by Django 2.2b1 on 2019-03-01 14:54

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190224_0515'),
        ('combat', '0007_gmscreentab_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('_generic_name', models.CharField(blank=True, db_column='generic_name', max_length=255, null=True)),
                ('proficiency', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('challenge', models.CharField(blank=True, max_length=3, null=True)),
                ('size', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tiny'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Huge'), (6, 'Gargantuan'), (7, 'Colossal')], null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('alignment', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'lawful good'), (2, 'neutral good'), (3, 'chaotic good'), (4, 'lawful neutral'), (5, 'neutral'), (6, 'chaotic neutral'), (7, 'lawful evil'), (8, 'neutral evil'), (9, 'chaotic evil'), (0, 'unaligned')], null=True)),
                ('armor_class', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('armor_kind', models.CharField(blank=True, max_length=255, null=True)),
                ('hit_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_hit_die', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('hit_die_size', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12'), (20, 'd20'), (100, 'd100')], default=4)),
                ('speed', models.CharField(blank=True, max_length=100, null=True)),
                ('str', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('dex', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('con', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('int', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('wis', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('cha', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('saving_throws', models.CharField(blank=True, max_length=50, null=True)),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('senses', models.CharField(blank=True, max_length=255, null=True)),
                ('damage_vulnerabilities', models.TextField(blank=True, null=True)),
                ('damage_resistances', models.TextField(blank=True, null=True)),
                ('damage_immunities', models.TextField(blank=True, null=True)),
                ('condition_immunities', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='combat_statblock_owned_set', to='accounts.Campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
