# Generated by Django 2.2b1 on 2019-03-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0008_statblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statblock',
            name='hit_die_size',
        ),
        migrations.AlterField(
            model_name='statblock',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tiny'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Huge'), (6, 'Gargantuan')], null=True),
        ),
    ]
