# Generated by Django 2.2b1 on 2019-03-03 00:21

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190224_0515'),
        ('combat', '0009_auto_20190302_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('save_dc_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('save_source_ability', models.CharField(blank=True, choices=[('str', 'str'), ('dex', 'dex'), ('con', 'con'), ('int', 'int'), ('wis', 'wis'), ('cha', 'cha')], max_length=3, null=True)),
                ('save_ability', models.CharField(blank=True, choices=[('str', 'str'), ('dex', 'dex'), ('con', 'con'), ('int', 'int'), ('wis', 'wis'), ('cha', 'cha')], max_length=3, null=True)),
                ('prop_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'creature property'), (2, 'action'), (3, 'legendary action'), (4, 'reaction')], default=2)),
                ('attack_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'melee weapon attack'), (2, 'ranged weapon attack'), (3, 'melee spell attack'), (4, 'ranged spell attack')], null=True)),
                ('uses_ability_mod', models.CharField(blank=True, choices=[('str', 'str'), ('dex', 'dex'), ('con', 'con'), ('int', 'int'), ('wis', 'wis'), ('cha', 'cha')], max_length=3, null=True)),
                ('tohit_bonus_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reach_range', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('range_second', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_targets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit_num_damage_dice', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit_die_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit_damage_type', models.TextField(blank=True, null=True)),
                ('hit_extra_damage_dice', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit_extra_damage_die_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit_extra_damage_type', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='combat_creatureprop_owned_set', to='accounts.Campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatblockProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True)),
                ('manual_ordering', models.SmallIntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='combat_statblockprop_owned_set', to='accounts.Campaign')),
                ('creature_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combat.CreatureProp')),
                ('statblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combat.Statblock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
