# Generated by Django 2.2b1 on 2019-03-09 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0010_creatureprop_statblockprop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatant',
            name='effects',
        ),
        migrations.AddField(
            model_name='combatant',
            name='buffs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatant',
            name='debuffs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatant',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatant',
            name='statblock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='combat.Statblock'),
        ),
        migrations.AddField(
            model_name='creatureprop',
            name='statblock_set',
            field=models.ManyToManyField(blank=True, through='combat.StatblockProp', to='combat.Statblock'),
        ),
    ]
